-- $Id: manifest.lua 10204 2024-08-08 15:49:23Z cfrees $
---------------------------------------------------------------------
-- paid â defnyddio am packages arkandis - gweler arkandis-manifest.lua yn lle
-- y ffeil hwn
-- dim yn addas ar gyfer ffontiau yn gyffredinol
-- local derivedfiles = derivedfiles or {"*.cls", "*.sty"}
-- local buildscripts = buildscripts or  {"*.lua", "Makefile"}
-- local testfiles = testfiles or {"*.lvt","*.pvt","*.tlg","*.lve","*.tpf"}
function populatescripts()
  local sourcefiledir = sourcefiledir or "."
  if buildscripts == nil then
    -- local bldscripts = {}
    local bldscripts = ""
    local possscripts = {sourcefiledir .. "/build.lua", maindir .. "/adnoddau/manifest.lua"}
    for i,j in ipairs(possscripts) do
      if fileexists(j) then
        bldscripts = bldscripts .. "\n* " .. basename(j) 
      end
    end
    return bldscripts
  else
    return buildscripts
  end
end
function populatedoc()
  local docs = docs  or {typesetfiles,typesetdemofiles}
  local tmpdocs = ""
  for i,j in ipairs(docs) do
    for k,l in ipairs(j) do
      tmpdocs = tmpdocs .. "\n* " .. l
    end
  end
  return string.gsub(tmpdocs, "%.$w+$", ".pdf")
end
function populatetxt()
  local txts = textfiles or {}
  local tmptxts = ""
  for i,j in ipairs(txts) do
    local tmptexts = filelist(sourcefiledir,j)
    for k,l in ipairs(tmptexts) do
      if not ( l == "." or l == ".." ) then
        tmptxts = tmptxts .. "\n* " .. l
      end
    end
  end
  if not string.match(tmptxts, ctanreadme) then
    if fileexists(sourcefiledir, ctanreadme) then
      local tmptexts = filelist(sourcefiledir, ctanreadme)
      for i,j in ipairs(tmptexts) do
        tmptxts = tmptxts .. "\n* " .. j
      end
    end
  end
  if not string.match(tmptxts, manifestfile) then
    if fileexists(sourcefiledir, manifestfile) then
      local tmptexts = filelist(sourcefiledir, manifestfile)
      for i,j in ipairs(tmptexts) do
        tmptxts = tmptxts .. "\n* " .. j
      end
    end
  end
  return tmptxts
end
----------------------------------------------------------------------
function manifest_write_opening(filehandle)
  local date  = date or os.date()
  filehandle:write( "# Manifest for " .. ctanpkg .. "\n\nCopyright (C) " .. date .. " Clea F. Rees\n\n" )
  filehandle:write(
    [[This work may be distributed and/or modified under the conditions of the LaTeX
Project Public License, either version 1.3c of this license or (at your option)
any later version.  The latest version of this license is in
      https://www.latex-project.org/lppl.txt
and version 1.3 or later is part of all distributions of LaTeX version 
2008-05-04 or later.

This work has the LPPL maintenance status `maintained'.

The Current Maintainer of this work is Clea F. Rees.

This work consists of all files listed in manifest.txt.

This file was automatically generated by `l3build manifest`.]]
  )
end
---------------------------------------------------------------------
function manifest_setup ()
  if not ( fileexists(unpackdir .. "/" .. module .. ".sty") or fileexists(unpackdir .. "/" .. ctanpkg .. ".sty") ) then
    unpack()
  end
  local buildscripts = populatescripts()
  local docfiles = populatedoc()
  local txtfiles = populatetxt() 
  local groups = {
    {
      subheading = "Source files",
    },
    {
      name = "Package files",
      dir = sourcefiledir,
      files = {sourcefiles,typesetfiles,typesetsourcefiles,typesetdemofiles},
      exclude = {derivedfiles},
      description = txtfiles,
    },
    {
      name = "Development files",
      dir = testfiledir,
      files = {"*" .. lvtext, "*" .. lveext, "*" .. tlgext, "*" .. pvtext, "*" .. tpfext},
      description = buildscripts, 
      -- exclude = {ctanpkg .. "-test.lvt", module .. "-test.lvt"},
    },
    {
      subheading = "Derived files",
    },
    {
      name = "Package files",
      files = {"*.cls","*.sty"},
      dir = unpackdir,
      exclude = {".",".."},
      -- description = derfiles,
    },
    {
      name = "Typeset documentation",
      files = {typesetfiles,typesetdemofiles,textfiles},
      excludefiles = {".",".."},
      dir = typesetdir,
      rename = {"%.%w+$",".pdf"},
    },
  }
  return groups
end
---------------------------------------------------------------------
-- vim: ts=2:sw=2:tw=80:nospell:
